### ISSUE TITLE
BPM turn off

### ISSUE THREAD

**Issue by Steffielight** [bitfocus/companion-module-thelightingcontroller#12]
Hi,

I use bitfocus for my stream deck xl . controlling lighting with quick dmx software. I have a problem with BPM. I use virtual dj for BPM signal to quick dmx. Now bitfocus send a standard  BPM signal to quick dmx. That give a error with the software. 2 software send BPM.

How turn off BPM in bitfocus?

Like to read
![Schermafbeelding 2024-03-30 121923](https://github.com/bitfocus/companion-module-thelightingcontroller/assets/165475805/403c1187-3f2b-4ac9-8f40-d55cac1b43f4)

**Comment by Steffielight** [comment]
BPM off companion.   For quick dmx is it not possible to use music. Now the bpm from companion give the main bpm. Please make it possible to turn off. 


How i connect a light button from quick dmx to companion?

**Comment by thargy** [comment]
Please always look at existing issues before raising a new one. There were only 2 open issues when you opened this, and the top one asks exactly the same question!

There is a workaround - https://github.com/bitfocus/companion-module-thelightingcontroller/issues/6#issuecomment-1328033708

Closing as duplicate.
