### ISSUE TITLE
Warning Connected, waiting for server ready

### ISSUE THREAD

**Issue by TimoVinkk** [bitfocus/companion-module-thelightingcontroller#9]
Hi,

When trying to connect companion to QuickDMX im getting this error: 
![image](https://github.com/bitfocus/companion-module-thelightingcontroller/assets/26720952/b70eed65-957f-4208-82b6-710541c97c86)

Does anyone know how to fix this?

Thanks!

Edit: Thanks! For some reason i skipped the password part!

**Comment by thargy** [comment]
> Hi,
> 
> When trying to connect companion to QuickDMX im getting this error: ![image](https://user-images.githubusercontent.com/26720952/255665736-b70eed65-957f-4208-82b6-710541c97c86.png)
> 
> Does anyone know how to fix this?
> 
> Thanks!

Please provide more information, e.g.:

* Which version of Companion are you using?
* Have you followed the setup instructions in the [readme](/bitfocus/companion-module-thelightingcontroller/#setting-up-quickdmxtlcshowxpress)?

I suspect you're using the latest version 3 of Companion. Unfortunately, as you can see from #7, I haven't had time to complete the substantial code changes required to migrate the module to v.3.  I've just moved home and am in the middle of a massive renovation project - obviously contributions are welcome!

Alternatively, you can consider installing the [last currently supported version of Companion](https://github.com/bitfocus/companion/releases/tag/v2.4.2) and trying the module there first.

Please note: I haven't even tested on version 3 so it might work for all I know (but I suspect not).

**Comment by thargy** [comment]
> Edit: Thanks! For some reason i skipped the password part!

If you're using v.3 of Companion, I would like to know if it still works?
